# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=smartfields.fields.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
